Kriteria 3

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -27,7 +27,13 @@ jobs:
       working-directory: MLProject
       run: |
         python modelling.py
-        echo "MLflow Run ID: $(mlflow runs list --experiment-name=Learning_Resources_Experiment_New | grep 'RUN_ID' | awk '{print $2}' | head -n 1)" > run_id.txt
+        # Dapatkan ID run terakhir yang selesai
+        RUN_ID=$(mlflow runs list --experiment-name=Learning_Resources_Experiment_New --filter "status='FINISHED'" -max-results=1 | grep -oP '(?<=run_id=)[a-f0-9-]+')
+        if [ -z "$RUN_ID" ]; then
+          echo "Error: No finished run found"
+          exit 1
+        fi
+        echo "MLflow Run ID: $RUN_ID" > run_id.txt
 
     - name: Upload artifacts
       uses: actions/upload-artifact@v4
